// protein: grams per 100g of the food as eaten (cooked, unless noted)
// gramsPerUnit: typical weight of one `unit` — the calibration that makes "1 bowl" meaningful
// alias: extra spellings the text parser should match (bhurji/burji, dahi/curd, anda/egg…)
const FOODS = [
  /* --- staples & protein sources --- */
  { id:'paneer',   name:'Paneer',            emoji:'🧀', unit:'piece',  gramsPerUnit:50,  protein:18.0, alias:'panir cottage cheese' },
  { id:'whey',     name:'Whey protein',      emoji:'🥤', unit:'scoop',  gramsPerUnit:30,  protein:80.0, alias:'protein powder shake supplement' },
  { id:'egg',      name:'Egg (whole)',       emoji:'🥚', unit:'egg',    gramsPerUnit:50,  protein:12.6, alias:'anda boiled eggs' },
  { id:'eggwhite', name:'Egg white',         emoji:'🍳', unit:'white',  gramsPerUnit:33,  protein:10.9, alias:'egg whites safedi' },
  { id:'chicken',  name:'Chicken breast',    emoji:'🍗', unit:'piece',  gramsPerUnit:100, protein:31.0, alias:'murga murgh grilled chicken' },
  { id:'mutton',   name:'Mutton (cooked)',   emoji:'🍖', unit:'serving',gramsPerUnit:100, protein:25.0, alias:'lamb goat bakra' },
  { id:'fish',     name:'Fish (cooked)',     emoji:'🐟', unit:'fillet', gramsPerUnit:100, protein:19.0, alias:'rohu machli surmai' },
  { id:'prawns',   name:'Prawns',            emoji:'🦐', unit:'serving',gramsPerUnit:100, protein:20.0, alias:'shrimp jhinga' },
  { id:'dal',      name:'Dal (cooked)',      emoji:'🍲', unit:'katori', gramsPerUnit:150, protein:4.5,  alias:'daal lentils tadka toor arhar' },
  { id:'rajma',    name:'Rajma (cooked)',    emoji:'🫘', unit:'katori', gramsPerUnit:150, protein:8.7,  alias:'kidney beans' },
  { id:'chana',    name:'Chole / chickpeas', emoji:'🫘', unit:'katori', gramsPerUnit:150, protein:8.9,  alias:'chhole chana chickpea kabuli' },
  { id:'sprouts',  name:'Sprouts',           emoji:'🌱', unit:'bowl',   gramsPerUnit:100, protein:7.6,  alias:'moong sprout ankurit' },
  { id:'soya',     name:'Soya chunks (dry)', emoji:'🟤', unit:'cup dry',gramsPerUnit:50,  protein:52.0, alias:'nutrela meal maker' },
  { id:'soyacook', name:'Soya chunks (cooked)',emoji:'🟤',unit:'katori',gramsPerUnit:150, protein:16.0, alias:'nutrela sabzi' },
  { id:'tofu',     name:'Tofu',              emoji:'⬜', unit:'block',  gramsPerUnit:100, protein:8.0,  alias:'bean curd' },
  { id:'curd',     name:'Curd / dahi',       emoji:'🥛', unit:'katori', gramsPerUnit:150, protein:3.5,  alias:'dahi yogurt yoghurt' },
  { id:'greekyog', name:'Greek yogurt',      emoji:'🍨', unit:'cup',    gramsPerUnit:150, protein:10.0, alias:'hung curd epigamia' },
  { id:'milk',     name:'Milk',              emoji:'🥛', unit:'glass',  gramsPerUnit:250, protein:3.4,  alias:'doodh' },
  { id:'lassi',    name:'Lassi',             emoji:'🥤', unit:'glass',  gramsPerUnit:250, protein:3.0,  alias:'sweet lassi' },
  { id:'chaas',    name:'Buttermilk / chaas',emoji:'🥛', unit:'glass',  gramsPerUnit:250, protein:1.5,  alias:'chhach mattha' },
  { id:'cheese',   name:'Cheese slice',      emoji:'🧀', unit:'slice',  gramsPerUnit:20,  protein:25.0, alias:'amul cheese' },

  /* --- carbs & breads --- */
  { id:'roti',     name:'Roti / chapati',    emoji:'🫓', unit:'roti',   gramsPerUnit:40,  protein:8.1,  alias:'chapatti phulka fulka' },
  { id:'paratha',  name:'Paratha (plain)',   emoji:'🫓', unit:'paratha',gramsPerUnit:80,  protein:7.0,  alias:'parantha' },
  { id:'alooparatha',name:'Aloo paratha',    emoji:'🥔', unit:'paratha',gramsPerUnit:120, protein:5.5,  alias:'potato paratha' },
  { id:'poori',    name:'Poori',             emoji:'🫓', unit:'poori',  gramsPerUnit:35,  protein:7.0,  alias:'puri' },
  { id:'rice',     name:'Rice (cooked)',     emoji:'🍚', unit:'katori', gramsPerUnit:150, protein:2.7,  alias:'chawal chaawal white rice' },
  { id:'brownrice',name:'Brown rice (cooked)',emoji:'🍚',unit:'katori', gramsPerUnit:150, protein:2.6,  alias:'' },
  { id:'quinoa',   name:'Quinoa (cooked)',   emoji:'🌾', unit:'katori', gramsPerUnit:150, protein:4.4,  alias:'' },
  { id:'bread',    name:'Bread slice',       emoji:'🍞', unit:'slice',  gramsPerUnit:30,  protein:9.0,  alias:'white bread toast' },
  { id:'brownbread',name:'Brown bread slice',emoji:'🍞', unit:'slice',  gramsPerUnit:35,  protein:11.0, alias:'multigrain wheat bread' },
  { id:'oats',     name:'Oats (dry)',        emoji:'🥣', unit:'cup dry',gramsPerUnit:40,  protein:13.0, alias:'oatmeal quaker' },
  { id:'muesli',   name:'Muesli',            emoji:'🥣', unit:'bowl',   gramsPerUnit:50,  protein:10.0, alias:'granola' },

  /* --- cooked dishes --- */
  { id:'paneerbhurji',name:'Paneer bhurji',  emoji:'🍳', unit:'katori', gramsPerUnit:150, protein:13.0, alias:'burji bhurjee panir bhurji scrambled paneer' },
  { id:'eggbhurji',name:'Egg bhurji',        emoji:'🍳', unit:'katori', gramsPerUnit:150, protein:11.0, alias:'anda burji scrambled egg' },
  { id:'omelette', name:'Omelette',          emoji:'🍳', unit:'omelette',gramsPerUnit:120,protein:13.0, alias:'omlet omlette amlet' },
  { id:'paneertikka',name:'Paneer tikka',    emoji:'🍢', unit:'plate',  gramsPerUnit:150, protein:20.0, alias:'grilled paneer' },
  { id:'palakpaneer',name:'Palak paneer',    emoji:'🥬', unit:'katori', gramsPerUnit:150, protein:9.0,  alias:'saag paneer' },
  { id:'matarpaneer',name:'Matar / shahi paneer',emoji:'🍛',unit:'katori',gramsPerUnit:150,protein:9.0, alias:'paneer butter masala kadai shahi matar' },
  { id:'chickencurry',name:'Chicken curry',  emoji:'🍛', unit:'katori', gramsPerUnit:150, protein:14.0, alias:'butter chicken murgh masala kadai chicken' },
  { id:'chickentikka',name:'Chicken tikka',  emoji:'🍢', unit:'plate',  gramsPerUnit:150, protein:27.0, alias:'tandoori chicken grilled' },
  { id:'eggcurry', name:'Egg curry',         emoji:'🍛', unit:'katori', gramsPerUnit:150, protein:9.0,  alias:'anda curry' },
  { id:'fishcurry',name:'Fish curry',        emoji:'🐟', unit:'katori', gramsPerUnit:150, protein:12.0, alias:'machli curry' },
  { id:'dalmakhani',name:'Dal makhani',      emoji:'🍲', unit:'katori', gramsPerUnit:150, protein:6.0,  alias:'kali dal maa ki dal' },
  { id:'kadhi',    name:'Kadhi',             emoji:'🍲', unit:'katori', gramsPerUnit:150, protein:3.5,  alias:'kadi pakora kadhi' },
  { id:'sambar',   name:'Sambar',            emoji:'🍲', unit:'katori', gramsPerUnit:150, protein:3.0,  alias:'sambhar' },
  { id:'khichdi',  name:'Khichdi',           emoji:'🍚', unit:'katori', gramsPerUnit:180, protein:4.5,  alias:'khichri kichdi' },
  { id:'rajmarice',name:'Rajma chawal',      emoji:'🍛', unit:'plate',  gramsPerUnit:350, protein:5.4,  alias:'rajma rice' },
  { id:'curdrice', name:'Curd rice',         emoji:'🍚', unit:'katori', gramsPerUnit:180, protein:3.0,  alias:'dahi chawal thayir sadam' },
  { id:'biryani',  name:'Chicken biryani',   emoji:'🍛', unit:'plate',  gramsPerUnit:300, protein:8.0,  alias:'chicken pulao' },
  { id:'vegbiryani',name:'Veg biryani / pulao',emoji:'🍚',unit:'plate', gramsPerUnit:300, protein:3.5,  alias:'pulav veg biryani' },
  { id:'chana chaat',name:'Chana chaat',     emoji:'🥗', unit:'bowl',   gramsPerUnit:150, protein:8.0,  alias:'chole chaat boiled chana' },
  { id:'pavbhaji', name:'Pav bhaji',         emoji:'🍞', unit:'plate',  gramsPerUnit:300, protein:3.5,  alias:'bhaji pav' },
  { id:'cholebhat',name:'Chole bhature',     emoji:'🍛', unit:'plate',  gramsPerUnit:300, protein:7.0,  alias:'chhole bhature' },
  { id:'maggi',    name:'Maggi (cooked)',    emoji:'🍜', unit:'pack',   gramsPerUnit:180, protein:4.5,  alias:'noodles instant ramen' },
  { id:'pasta',    name:'Pasta (cooked)',    emoji:'🍝', unit:'bowl',   gramsPerUnit:200, protein:5.5,  alias:'macaroni penne white sauce' },
  { id:'pizza',    name:'Pizza slice',       emoji:'🍕', unit:'slice',  gramsPerUnit:110, protein:11.0, alias:'dominos' },
  { id:'burger',   name:'Burger',            emoji:'🍔', unit:'burger', gramsPerUnit:200, protein:12.0, alias:'mcdonalds' },
  { id:'sandwich', name:'Veg sandwich',      emoji:'🥪', unit:'sandwich',gramsPerUnit:150,protein:8.0,  alias:'grilled sandwich' },

  /* --- south indian & snacks --- */
  { id:'idli',     name:'Idli',              emoji:'⚪', unit:'idli',   gramsPerUnit:40,  protein:4.5,  alias:'idly' },
  { id:'dosa',     name:'Dosa',              emoji:'🥞', unit:'dosa',   gramsPerUnit:90,  protein:4.0,  alias:'masala dosa dose' },
  { id:'uttapam',  name:'Uttapam',           emoji:'🥞', unit:'uttapam',gramsPerUnit:120, protein:4.5,  alias:'uthappam' },
  { id:'vada',     name:'Medu vada',         emoji:'🍩', unit:'vada',   gramsPerUnit:50,  protein:6.0,  alias:'wada' },
  { id:'upma',     name:'Upma',              emoji:'🥣', unit:'katori', gramsPerUnit:180, protein:3.0,  alias:'uppma' },
  { id:'poha',     name:'Poha',              emoji:'🍚', unit:'plate',  gramsPerUnit:200, protein:2.5,  alias:'pohe aval' },
  { id:'besan',    name:'Besan chilla',      emoji:'🥞', unit:'chilla', gramsPerUnit:80,  protein:8.0,  alias:'cheela chila besan chila' },
  { id:'moongchilla',name:'Moong dal chilla',emoji:'🥞', unit:'chilla', gramsPerUnit:80,  protein:9.0,  alias:'moong cheela pesarattu' },
  { id:'dhokla',   name:'Dhokla',            emoji:'🟨', unit:'piece',  gramsPerUnit:40,  protein:6.0,  alias:'khaman' },
  { id:'samosa',   name:'Samosa',            emoji:'🥟', unit:'samosa', gramsPerUnit:60,  protein:5.0,  alias:'singhara' },
  { id:'pakora',   name:'Pakora',            emoji:'🧅', unit:'plate',  gramsPerUnit:100, protein:6.0,  alias:'bhaji fritters bhajiya' },
  { id:'momos',    name:'Momos (veg)',       emoji:'🥟', unit:'piece',  gramsPerUnit:30,  protein:6.0,  alias:'dumpling' },

  /* --- nuts, seeds, fruit, extras --- */
  { id:'peanuts',  name:'Peanuts',           emoji:'🥜', unit:'handful',gramsPerUnit:30,  protein:26.0, alias:'moongphali groundnut' },
  { id:'peanutbtr',name:'Peanut butter',     emoji:'🥜', unit:'tbsp',   gramsPerUnit:16,  protein:25.0, alias:'pb' },
  { id:'almonds',  name:'Almonds',           emoji:'🌰', unit:'handful',gramsPerUnit:28,  protein:21.0, alias:'badam' },
  { id:'walnuts',  name:'Walnuts',           emoji:'🌰', unit:'handful',gramsPerUnit:28,  protein:15.0, alias:'akhrot' },
  { id:'cashews',  name:'Cashews',           emoji:'🌰', unit:'handful',gramsPerUnit:28,  protein:18.0, alias:'kaju' },
  { id:'pumpkinseed',name:'Pumpkin seeds',   emoji:'🎃', unit:'handful',gramsPerUnit:28,  protein:30.0, alias:'seeds' },
  { id:'chia',     name:'Chia seeds',        emoji:'⚫', unit:'tbsp',   gramsPerUnit:12,  protein:17.0, alias:'sabja' },
  { id:'banana',   name:'Banana',            emoji:'🍌', unit:'banana', gramsPerUnit:120, protein:1.1,  alias:'kela' },
  { id:'apple',    name:'Apple',             emoji:'🍎', unit:'apple',  gramsPerUnit:180, protein:0.3,  alias:'seb' },
  { id:'proteinbar',name:'Protein bar',      emoji:'🍫', unit:'bar',    gramsPerUnit:60,  protein:33.0, alias:'yoga bar' },

  /* --- raw:true — ingredients for the recipe builder, hidden from the logging lists --- */
  { id:'i_besan',  name:'Besan / gram flour',  emoji:'🟡', unit:'cup',  gramsPerUnit:100, protein:22.0, raw:true },
  { id:'i_atta',   name:'Atta / wheat flour',  emoji:'🌾', unit:'cup',  gramsPerUnit:120, protein:12.0, raw:true },
  { id:'i_maida',  name:'Maida',               emoji:'⬜', unit:'cup',  gramsPerUnit:120, protein:10.0, raw:true },
  { id:'i_suji',   name:'Suji / rava',         emoji:'🟨', unit:'cup',  gramsPerUnit:160, protein:12.0, raw:true },
  { id:'i_rice',   name:'Rice (raw)',          emoji:'🍚', unit:'cup',  gramsPerUnit:180, protein:7.0,  raw:true },
  { id:'i_moong',  name:'Moong dal (raw)',     emoji:'🟢', unit:'cup',  gramsPerUnit:200, protein:24.0, raw:true },
  { id:'i_toor',   name:'Toor dal (raw)',      emoji:'🟠', unit:'cup',  gramsPerUnit:200, protein:22.0, raw:true },
  { id:'i_chana',  name:'Chana dal (raw)',     emoji:'🟤', unit:'cup',  gramsPerUnit:200, protein:20.0, raw:true },
  { id:'i_rajma',  name:'Rajma (raw)',         emoji:'🫘', unit:'cup',  gramsPerUnit:180, protein:23.0, raw:true },
  { id:'i_chole',  name:'Chickpeas (raw)',     emoji:'🫘', unit:'cup',  gramsPerUnit:180, protein:19.0, raw:true },
  { id:'i_water',  name:'Water',               emoji:'💧', unit:'cup',  gramsPerUnit:240, protein:0,    raw:true },
  { id:'i_oil',    name:'Oil / ghee',          emoji:'🫗', unit:'tbsp', gramsPerUnit:14,  protein:0,    raw:true },
  { id:'i_onion',  name:'Onion',               emoji:'🧅', unit:'medium',gramsPerUnit:110,protein:1.1,  raw:true },
  { id:'i_tomato', name:'Tomato',              emoji:'🍅', unit:'medium',gramsPerUnit:120,protein:0.9,  raw:true },
  { id:'i_potato', name:'Potato',              emoji:'🥔', unit:'medium',gramsPerUnit:150,protein:2.0,  raw:true },
  { id:'i_spinach',name:'Spinach / palak',     emoji:'🥬', unit:'bowl', gramsPerUnit:100, protein:2.9,  raw:true },
  { id:'i_capsi',  name:'Capsicum',            emoji:'🫑', unit:'medium',gramsPerUnit:100,protein:0.9,  raw:true },
  { id:'i_sugar',  name:'Sugar',               emoji:'🍬', unit:'tsp',  gramsPerUnit:5,   protein:0,    raw:true }
];
